### ISSUE TITLE
Wrong Citation?

### ISSUE THREAD

**Issue by pplanel** [minosvasilias/godot-dodo#3]
https://github.com/sahil280114/codealpaca

**Comment by minosvasilias** [comment]
Can you expand on what you mean?

**Comment by pplanel** [comment]
https://arxiv.org/abs/2212.10560

**Comment by pplanel** [comment]
This repo is specialization of the referenced paper and repo. You probably should correctly cite the sources of the hard working researchers.

**Comment by pplanel** [comment]
> The godot-dodo project presents a pipeline to finetune open source language models on human-created, language-specific code retrieved from GitHub.

**Comment by minosvasilias** [comment]
Understood, thank you.
I would say the data generation process differs quite significantly from the self-instruct paper, but it's true that `stanford-alpaca` (which `codealpaca` seems to be another modification of) has been heavily referenced. 

I'll add that to the readme.

**Comment by minosvasilias** [comment]
Resolved here: https://github.com/minosvasilias/godot-dodo/pull/4
